name: Deploy HTML to GitHub Pages

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
      FOLDER_ID: ${{ secrets.FOLDER_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 

    - name: Run Python Script to Generate HTML
      run: python -u minogami.py
